"use client";

import { useMemo, useState } from "react";

type AnalysisResult = {
  severity: string;
  priority: string;
  category: string;
  summary: string;
  business_impact: string;
  recommended_actions: string[];
};

type TicketStatus = "New" | "Investigating" | "Resolved";

type HistoryItem = {
  id: number;
  ticket: string;
  analysis: AnalysisResult;
  status: TicketStatus;
};

type ActivityItem = {
  id: number;
  message: string;
  timestamp: string;
  type: "analysis" | "status" | "export";
};

export default function Home() {
  const [ticket, setTicket] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [history, setHistory] = useState<HistoryItem[]>([]);
  const [activities, setActivities] = useState<ActivityItem[]>([]);
  const [error, setError] = useState("");

  const [searchQuery, setSearchQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("All");
  const [severityFilter, setSeverityFilter] = useState("All");

  const addActivity = (
    message: string,
    type: ActivityItem["type"]
  ) => {
    setActivities((prev) => [
      {
        id: Date.now(),
        message,
        timestamp: new Date().toLocaleString(),
        type,
      },
      ...prev,
    ]);
  };

  const analyzeTicket = async () => {
    if (!ticket.trim()) {
      setError("Please enter a support ticket before analyzing.");
      return;
    }

    setLoading(true);
    setError("");
    setResult(null);

    try {
      const response = await fetch("http://localhost:5000/api/triage", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ ticket }),
      });

      const data = await response.json();

      if (!data.success) {
        throw new Error(data.error || "Analysis failed");
      }

      setResult(data.analysis);

      setHistory((prev) => [
        {
          id: Date.now(),
          ticket,
          analysis: data.analysis,
          status: "New",
        },
        ...prev,
      ]);

      addActivity(
        `${data.analysis.severity} ${data.analysis.category} incident analyzed.`,
        "analysis"
      );

      setTicket("");
    } catch (err: any) {
      setError(err.message || "Something went wrong");
    } finally {
      setLoading(false);
    }
  };

  const updateTicketStatus = (id: number, status: TicketStatus) => {
    setHistory((prev) =>
      prev.map((item) => {
        if (item.id === id) {
          addActivity(`Ticket moved to ${status} status.`, "status");
          return { ...item, status };
        }

        return item;
      })
    );
  };

  const exportIncidentReport = () => {
    if (!result) return;

    addActivity("Incident report exported.", "export");

    const reportWindow = window.open("", "_blank");

    if (!reportWindow) return;

    const reportHtml = `
      <html>
        <head>
          <title>AI Incident Report</title>
          <style>
            body {
              font-family: Arial, sans-serif;
              padding: 40px;
              color: #111827;
              line-height: 1.6;
            }

            h1 {
              color: #2563eb;
            }

            h2 {
              margin-top: 30px;
            }

            .badge {
              display: inline-block;
              padding: 8px 14px;
              border-radius: 8px;
              font-weight: bold;
              margin-right: 10px;
              margin-top: 10px;
            }

            .severity {
              background: #fee2e2;
              color: #dc2626;
            }

            .priority {
              background: #fef3c7;
              color: #d97706;
            }

            .category {
              background: #dbeafe;
              color: #2563eb;
            }

            .section {
              margin-top: 25px;
            }

            ul {
              padding-left: 20px;
            }
          </style>
        </head>

        <body>
          <h1>AI Operational Incident Report</h1>

          <p>Generated by AI Support Ticket Triage Platform</p>

          <div>
            <span class="badge severity">Severity: ${result.severity}</span>
            <span class="badge priority">Priority: ${result.priority}</span>
            <span class="badge category">Category: ${result.category}</span>
          </div>

          <div class="section">
            <h2>Executive Summary</h2>
            <p>${result.summary}</p>
          </div>

          <div class="section">
            <h2>Business Impact</h2>
            <p>${result.business_impact}</p>
          </div>

          <div class="section">
            <h2>Recommended Actions</h2>
            <ul>
              ${result.recommended_actions
                .map((action) => `<li>${action}</li>`)
                .join("")}
            </ul>
          </div>

          <div class="section">
            <h2>Operational Insights</h2>
            <p>
              The AI operational engine identified this incident as a
              <strong>${result.priority}</strong> priority operational event
              within the <strong>${result.category}</strong> domain.
            </p>
          </div>

          <p style="margin-top:40px;color:#6b7280;font-size:13px;">
            Generated on: ${new Date().toLocaleString()}
          </p>
        </body>
      </html>
    `;

    reportWindow.document.write(reportHtml);
    reportWindow.document.close();
    reportWindow.focus();

    setTimeout(() => {
      reportWindow.print();
    }, 500);
  };

  const filteredHistory = useMemo(() => {
    return history.filter((item) => {
      const matchesSearch =
        item.ticket.toLowerCase().includes(searchQuery.toLowerCase()) ||
        item.analysis.category
          .toLowerCase()
          .includes(searchQuery.toLowerCase()) ||
        item.analysis.summary
          .toLowerCase()
          .includes(searchQuery.toLowerCase());

      const matchesStatus =
        statusFilter === "All" || item.status === statusFilter;

      const matchesSeverity =
        severityFilter === "All" ||
        item.analysis.severity === severityFilter;

      return matchesSearch && matchesStatus && matchesSeverity;
    });
  }, [history, searchQuery, statusFilter, severityFilter]);

  const metrics = useMemo(() => {
    const totalTickets = history.length;

    const criticalTickets = history.filter(
      (item) => item.analysis.severity.toLowerCase() === "critical"
    ).length;

    const highPriorityTickets = history.filter(
      (item) => item.analysis.priority.toLowerCase() === "high"
    ).length;

    const openTickets = history.filter(
      (item) => item.status !== "Resolved"
    ).length;

    const resolvedTickets = history.filter(
      (item) => item.status === "Resolved"
    ).length;

    const categoryCount: Record<string, number> = {};

    history.forEach((item) => {
      const category = item.analysis.category;
      categoryCount[category] = (categoryCount[category] || 0) + 1;
    });

    const mostCommonCategory =
      Object.entries(categoryCount).sort((a, b) => b[1] - a[1])[0]?.[0] ||
      "N/A";

    return {
      totalTickets,
      criticalTickets,
      highPriorityTickets,
      openTickets,
      resolvedTickets,
      mostCommonCategory,
      categoryCount,
    };
  }, [history]);

  const operationalInsights = useMemo(() => {
    if (history.length === 0) {
      return {
        topTrend: "No operational data available yet.",
        highestRisk: "Analyze tickets to generate insights.",
        recommendation: "AI operational recommendations will appear here.",
        summary: "The platform has not processed enough tickets yet.",
      };
    }

    const sortedCategories = Object.entries(metrics.categoryCount).sort(
      (a, b) => b[1] - a[1]
    );

    const topCategory = sortedCategories[0]?.[0] || "Unknown";
    const topCategoryCount = sortedCategories[0]?.[1] || 0;

    const unresolvedCritical = history.filter(
      (item) =>
        item.analysis.severity.toLowerCase() === "critical" &&
        item.status !== "Resolved"
    ).length;

    let recommendation = "Operational environment appears stable.";

    if (unresolvedCritical >= 2) {
      recommendation =
        "Multiple unresolved critical incidents detected. Immediate escalation is recommended.";
    } else if (metrics.openTickets >= 5) {
      recommendation =
        "Open operational ticket volume is increasing. Investigate recurring infrastructure instability.";
    }

    return {
      topTrend: `${topCategory} incidents represent ${topCategoryCount} analyzed operational events.`,
      highestRisk:
        unresolvedCritical > 0
          ? `${unresolvedCritical} unresolved critical incidents require immediate attention.`
          : "No unresolved critical incidents detected.",
      recommendation,
      summary: `The AI operational engine analyzed ${metrics.totalTickets} tickets with ${metrics.resolvedTickets} resolved and ${metrics.openTickets} currently active operational events.`,
    };
  }, [history, metrics]);

  return (
    <main className="min-h-screen bg-slate-950 text-white px-6 py-12">
      <div className="max-w-7xl mx-auto">
        <div className="mb-10">
          <h1 className="text-5xl font-bold mb-4">
            AI Support Ticket Triage
          </h1>

          <p className="text-slate-400 text-lg">
            AI-powered operational ticket analysis platform for DevOps and cloud
            infrastructure teams.
          </p>
        </div>

        <div className="grid md:grid-cols-3 lg:grid-cols-6 gap-6 mb-10">
          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl">
            <p className="text-slate-400 text-sm mb-2">Total Tickets</p>
            <h2 className="text-4xl font-bold text-white">
              {metrics.totalTickets}
            </h2>
          </div>

          <div className="bg-slate-900 border border-red-900 rounded-2xl p-6 shadow-xl">
            <p className="text-red-300 text-sm mb-2">Critical</p>
            <h2 className="text-4xl font-bold text-red-400">
              {metrics.criticalTickets}
            </h2>
          </div>

          <div className="bg-slate-900 border border-yellow-900 rounded-2xl p-6 shadow-xl">
            <p className="text-yellow-300 text-sm mb-2">High Priority</p>
            <h2 className="text-4xl font-bold text-yellow-400">
              {metrics.highPriorityTickets}
            </h2>
          </div>

          <div className="bg-slate-900 border border-orange-900 rounded-2xl p-6 shadow-xl">
            <p className="text-orange-300 text-sm mb-2">Open Tickets</p>
            <h2 className="text-4xl font-bold text-orange-400">
              {metrics.openTickets}
            </h2>
          </div>

          <div className="bg-slate-900 border border-green-900 rounded-2xl p-6 shadow-xl">
            <p className="text-green-300 text-sm mb-2">Resolved</p>
            <h2 className="text-4xl font-bold text-green-400">
              {metrics.resolvedTickets}
            </h2>
          </div>

          <div className="bg-slate-900 border border-blue-900 rounded-2xl p-6 shadow-xl">
            <p className="text-blue-300 text-sm mb-2">Top Category</p>
            <h2 className="text-2xl font-bold text-blue-400">
              {metrics.mostCommonCategory}
            </h2>
          </div>
        </div>

        <div className="mb-10 bg-slate-900 border border-slate-800 rounded-2xl p-8 shadow-2xl">
          <div className="flex items-center justify-between mb-8">
            <div>
              <h2 className="text-3xl font-bold">
                Real-Time Operational Feed
              </h2>

              <p className="text-slate-400 mt-2">
                Live operational activity and incident lifecycle tracking.
              </p>
            </div>

            <div className="bg-green-500/10 text-green-300 px-4 py-2 rounded-xl border border-green-500/20">
              Live Events
            </div>
          </div>

          <div className="space-y-4 max-h-96 overflow-y-auto">
            {activities.length === 0 && (
              <div className="bg-slate-950 border border-slate-800 rounded-xl p-6 text-slate-400">
                No operational activity detected yet.
              </div>
            )}

            {activities.map((activity) => (
              <div
                key={activity.id}
                className="bg-slate-950 border border-slate-800 rounded-xl p-5"
              >
                <div className="flex items-start justify-between gap-4">
                  <div>
                    <p className="text-slate-200 font-medium">
                      {activity.message}
                    </p>

                    <p className="text-slate-500 text-sm mt-2">
                      {activity.timestamp}
                    </p>
                  </div>

                  <div
                    className={`px-3 py-1 rounded-lg text-xs font-semibold ${
                      activity.type === "analysis"
                        ? "bg-blue-500/20 text-blue-300"
                        : activity.type === "status"
                        ? "bg-yellow-500/20 text-yellow-300"
                        : "bg-green-500/20 text-green-300"
                    }`}
                  >
                    {activity.type.toUpperCase()}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="mb-10 bg-slate-900 border border-slate-800 rounded-2xl p-8 shadow-2xl">
          <div className="flex items-center justify-between mb-8">
            <div>
              <h2 className="text-3xl font-bold">AI Operational Insights</h2>
              <p className="text-slate-400 mt-2">
                AI-generated operational intelligence based on analyzed ticket
                trends.
              </p>
            </div>

            <div className="bg-blue-500/10 text-blue-300 px-4 py-2 rounded-xl border border-blue-500/20">
              AI Powered
            </div>
          </div>

          <div className="grid md:grid-cols-2 gap-6">
            <div className="bg-slate-950 border border-slate-800 rounded-xl p-6">
              <h3 className="text-lg font-semibold mb-3 text-blue-400">
                Top Operational Trend
              </h3>
              <p className="text-slate-300">{operationalInsights.topTrend}</p>
            </div>

            <div className="bg-slate-950 border border-slate-800 rounded-xl p-6">
              <h3 className="text-lg font-semibold mb-3 text-red-400">
                Highest Risk Area
              </h3>
              <p className="text-slate-300">
                {operationalInsights.highestRisk}
              </p>
            </div>

            <div className="bg-slate-950 border border-slate-800 rounded-xl p-6">
              <h3 className="text-lg font-semibold mb-3 text-yellow-400">
                Operational Recommendation
              </h3>
              <p className="text-slate-300">
                {operationalInsights.recommendation}
              </p>
            </div>

            <div className="bg-slate-950 border border-slate-800 rounded-xl p-6">
              <h3 className="text-lg font-semibold mb-3 text-green-400">
                Operational Summary
              </h3>
              <p className="text-slate-300">{operationalInsights.summary}</p>
            </div>
          </div>
        </div>

        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-2xl">
          <label className="block text-lg font-semibold mb-4">
            Support Ticket
          </label>

          <textarea
            value={ticket}
            onChange={(e) => setTicket(e.target.value)}
            placeholder="Example: Production API returning 503 errors after latest deployment..."
            className="w-full h-40 rounded-xl bg-slate-950 border border-slate-700 p-4 text-white resize-none focus:outline-none focus:ring-2 focus:ring-blue-500"
          />

          <div className="flex flex-wrap gap-4 mt-5">
            <button
              onClick={analyzeTicket}
              disabled={loading}
              className="bg-blue-600 hover:bg-blue-700 transition px-6 py-3 rounded-xl font-semibold disabled:opacity-50"
            >
              {loading ? "Analyzing Ticket..." : "Analyze Ticket"}
            </button>

            {result && (
              <button
                onClick={exportIncidentReport}
                className="bg-green-600 hover:bg-green-700 transition px-6 py-3 rounded-xl font-semibold"
              >
                Export Incident Report
              </button>
            )}
          </div>

          {error && (
            <div className="mt-6 bg-red-500/10 border border-red-500 text-red-300 p-4 rounded-xl">
              {error}
            </div>
          )}
        </div>

        {result && (
          <div className="mt-10 bg-slate-900 border border-slate-800 rounded-2xl p-8 shadow-2xl">
            <h2 className="text-3xl font-bold mb-8">AI Analysis Results</h2>

            <div className="grid md:grid-cols-3 gap-6 mb-8">
              <div className="bg-slate-950 border border-slate-800 rounded-xl p-5">
                <p className="text-slate-400 text-sm mb-2">Severity</p>
                <h3 className="text-2xl font-bold text-red-400">
                  {result.severity}
                </h3>
              </div>

              <div className="bg-slate-950 border border-slate-800 rounded-xl p-5">
                <p className="text-slate-400 text-sm mb-2">Priority</p>
                <h3 className="text-2xl font-bold text-yellow-400">
                  {result.priority}
                </h3>
              </div>

              <div className="bg-slate-950 border border-slate-800 rounded-xl p-5">
                <p className="text-slate-400 text-sm mb-2">Category</p>
                <h3 className="text-2xl font-bold text-blue-400">
                  {result.category}
                </h3>
              </div>
            </div>

            <div className="mb-8">
              <h3 className="text-xl font-semibold mb-3">Summary</h3>
              <div className="bg-slate-950 border border-slate-800 rounded-xl p-5 text-slate-300">
                {result.summary}
              </div>
            </div>

            <div className="mb-8">
              <h3 className="text-xl font-semibold mb-3">Business Impact</h3>
              <div className="bg-slate-950 border border-slate-800 rounded-xl p-5 text-slate-300">
                {result.business_impact}
              </div>
            </div>

            <div>
              <h3 className="text-xl font-semibold mb-3">
                Recommended Actions
              </h3>

              <div className="bg-slate-950 border border-slate-800 rounded-xl p-5">
                <ul className="space-y-3">
                  {result.recommended_actions.map((action, index) => (
                    <li
                      key={index}
                      className="flex items-start gap-3 text-slate-300"
                    >
                      <span className="text-green-400 mt-1">✔</span>
                      <span>{action}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        )}

        {history.length > 0 && (
          <div className="mt-10 bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-2xl">
            <h2 className="text-2xl font-bold mb-6">Search & Filters</h2>

            <div className="grid md:grid-cols-3 gap-4">
              <input
                type="text"
                placeholder="Search tickets..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="bg-slate-950 border border-slate-700 rounded-xl px-4 py-3 text-white"
              />

              <select
                value={statusFilter}
                onChange={(e) => setStatusFilter(e.target.value)}
                className="bg-slate-950 border border-slate-700 rounded-xl px-4 py-3 text-white"
              >
                <option>All</option>
                <option>New</option>
                <option>Investigating</option>
                <option>Resolved</option>
              </select>

              <select
                value={severityFilter}
                onChange={(e) => setSeverityFilter(e.target.value)}
                className="bg-slate-950 border border-slate-700 rounded-xl px-4 py-3 text-white"
              >
                <option>All</option>
                <option>Critical</option>
                <option>High</option>
                <option>Medium</option>
                <option>Low</option>
              </select>
            </div>
          </div>
        )}

        {history.length > 0 && (
          <div className="mt-10">
            <h2 className="text-3xl font-bold mb-6">Analysis History</h2>

            <div className="space-y-6">
              {filteredHistory.length === 0 && (
                <div className="bg-slate-900 border border-slate-800 rounded-2xl p-8 text-center text-slate-400">
                  No tickets matched the current filters.
                </div>
              )}

              {filteredHistory.map((item) => (
                <div
                  key={item.id}
                  className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl"
                >
                  <div className="flex flex-wrap gap-3 mb-4">
                    <span className="bg-red-500/20 text-red-300 px-3 py-1 rounded-lg text-sm font-semibold">
                      {item.analysis.severity}
                    </span>

                    <span className="bg-yellow-500/20 text-yellow-300 px-3 py-1 rounded-lg text-sm font-semibold">
                      {item.analysis.priority}
                    </span>

                    <span className="bg-blue-500/20 text-blue-300 px-3 py-1 rounded-lg text-sm font-semibold">
                      {item.analysis.category}
                    </span>

                    <span
                      className={`px-3 py-1 rounded-lg text-sm font-semibold ${
                        item.status === "Resolved"
                          ? "bg-green-500/20 text-green-300"
                          : item.status === "Investigating"
                          ? "bg-yellow-500/20 text-yellow-300"
                          : "bg-orange-500/20 text-orange-300"
                      }`}
                    >
                      {item.status}
                    </span>
                  </div>

                  <div className="mb-4">
                    <select
                      value={item.status}
                      onChange={(e) =>
                        updateTicketStatus(
                          item.id,
                          e.target.value as TicketStatus
                        )
                      }
                      className="bg-slate-950 border border-slate-700 rounded-lg px-4 py-2 text-sm text-white"
                    >
                      <option value="New">New</option>
                      <option value="Investigating">Investigating</option>
                      <option value="Resolved">Resolved</option>
                    </select>
                  </div>

                  <p className="text-slate-300 mb-3">{item.ticket}</p>

                  <p className="text-slate-500 text-sm">
                    {item.analysis.summary}
                  </p>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </main>
  );
}